using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "synchronization context is known")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not a public API")]

// to be fixed later
[assembly: SuppressMessage("Code", "PCR0002:Await or Capture Tasks", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1000:Keywords should be spaced correctly", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1011:Closing square brackets should be spaced correctly", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1024:Colons Should Be Spaced Correctly", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1026:Code should not contain space after new or stackalloc keyword in implicitly typed array allocation", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1102:Query clause should follow previous clause", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1106:Code should not contain empty statements", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1121:Use built-in type alias", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1131:Use readable conditions", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1133:Do not combine attributes", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1136:Enum values should be on separate lines", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1209:Using alias directives should be placed after other using directives", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1212:Property accessors should follow order", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1309:Field names should not begin with underscore", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1500:Braces for multi-line statements should not share line", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1506:Element documentation headers should not be followed by blank line", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1512:Single-line comments should not be followed by blank line", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1517:Code should not contain blank lines at start of file", Justification = "will fix later")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1518:Use line endings correctly at end of file", Justification = "will fix later")]
